/*
 * RTaskResult.java
 *
 * Copyright (C) 2010-2016, Microsoft Corporation
 *
 * This program is licensed to you under the terms of Version 2.0 of the
 * Apache License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) for more details.
 *
 */
package com.revo.deployr.client.broker;

import com.revo.deployr.client.data.RData;

import java.net.URL;
import java.util.List;

/**
 * Represents a handle to the result generated by an
 * {@link com.revo.deployr.client.broker.RTask}.
 */
public interface RTaskResult {

    /**
     * <p>
     * Task DeployR identifier.
     * </p>
     * Maps to a project execution or job identifier.
     */
    public String getID();

    /**
     * Task type.
     */
    public RTaskType getType();

    /**
     * Task R session generated console output.
     */
    public String getGeneratedConsole();

    /**
     * Task R session graphics device generated plots.
     */
    public List<URL> getGeneratedPlots();

    /**
     * Task R session working directory generated files.
     */
    public List<URL> getGeneratedFiles();

    /**
     * Task R session workspace generated objects.
     */
    public List<RData> getGeneratedObjects();

    /**
     * Task generated files stored to DeployR repository.
     */
    public List<URL> getStoredFiles();

    /**
     * Task success indicator.
     */
    public boolean isSuccess();

    /**
     * Task interrupted indicator.
     */
    public boolean isInterrupted();

    /**
     * Task failure indicator.
     */
    public Exception getFailure();

    /**
     * Task time spent executing R code on server.
     */
    public long getTimeOnCode();

    /**
     * Task time spent being processed on server.
     */
    public long getTimeOnServer();

    /**
     * Task time spent on call to server.
     */
    public long getTimeOnCall();

}
